- app.js
- config.js.example
- history.js
* The *History* functions are now in their own module.
* There is a new config variable `DEFAULT_LOG_LOCATION` (suggested value: `.`).
* The log filename is `<DEFAULT_LOG_LOCATION>/echidna-<VERSION>.log`.
* Messages are appended to the log file with an automatic timestamp.
This is the second half of the work in the 2nd row in [the table of pending tasks](https://www.w3.org/Team/wiki/Publications_workflow_design#Summary); *"publication request form"*.
> Add simple logging, appending events and facts to a local text file

- CONTRIBUTING.md
- README.md
This creates a banner every time someone opens an issue or a pull request and gives explanations to contributors.
Along the way I made 2 guides that are pointed by this contribution reference ([Coding style guide](https://github.com/w3c/echidna/wiki/Coding-style-guide) and [Coding practices guide](https://github.com/w3c/echidna/wiki/Coding-practices-guide). I am in the process of finalizing them. I'll be happy to discuss these 2 but I figured it would make everyone save time by starting something and would also guide contributors rather than letting them in the blur. I'll be cleaning things only when everyone is okay with these and try to provide a linter configuration file.
I used *plenty* of references to make something as good as possible.
I gave a lot of love to these documents and I …
> Add a CONTRIBUTING.md file to the project

- README.md
- app.js
- functions.js
- lib/third-party-resources-checker.js
- package.json
- Move the checker in the lib folder
- Set up the checker as a npm dependency
- Use the checker's API interface instead of the spawnable command
Merging this will close #86.
> Set up the third party resources checker as lib

- .travis.yml
- README.md
- package.json
Code coverage can be run via `npm run coverage`.
The coveralls badge is updated after Travis builds.
> Code coverage

- test/drafts/frame-timing-2/meta.json
- test/drafts/frame-timing/meta.json
- test/drafts/navigation-timing/meta.json
- test/drafts/resource-timing/meta.json
- test/drafts/webrtc-stats/Overview.html
- test/drafts/webrtc-stats/meta.json
- test/views/behaviour.js
- test/views/index.html
- test/views/style.css
For instance, the method `api/status/` [requires now the ID of a publication job](https://github.com/w3c/echidna/commit/6196cef25da3ad9189282c4d383b883a3f9b5cb5#diff-0364f57fbff2fabbe941ed20c328ef1aR64) as a parameter.
> Change behaviour of the testbed to adapt to changes in the API

- app.js
This solution isn't too clean, but fixes the issue.
I'll look more into [the API of Express](http://expressjs.com/4x/api.html) and see if it'll be convenient to use Grunt to handle these directories depending on the environment.
> Fix express directory for static assets in both environments (prod and dev)

- app.js
- lib/document-downloader.js
- lib/history.js
- lib/job.js
- lib/json-http-service.js
- lib/orchestrator.js
- lib/publisher.js
- lib/request-state.js
- lib/third-party-resources-checker.js
- test/test.js
:warning: **READY TO BE REVIEWED BUT NO TESTS YET** :warning:
One of the ideas here is that `app.js` should get as little intelligence as possible.
The result is an `Orchestrator` that controls the process of publication. This class manipulates a frozen (immutable) state, `RequestState`. Basically, everything the `Orchestrator` does is manipulate a state that is given as an argument of the computation so that the outer state is never modified as a side effect. That way, we avoid unexpected changes.
To help with this and abstracting, the code makes use of higher-order functions (functions given as arguments or returned by other functions). This separates concerns because the code for a function makes little assumption on what an argument is supposed to do in addition to its type (for …
> Modular orchestrator

- test/test.js
w3c/specberus#173 added a few new possible errors; among them, [`latest-is-not-previous`](https://github.com/w3c/specberus/pull/173/files#diff-09f641a52baf89d6d1785acc66dafe97R172).
These three drafts used by the test suite are affected:
* `navigation-timing-2`
* `nav-csserror`
* `nav-csswarning`
This PR updates (adds one to) the total count of errors expected by mocha for these three test specs, thus fixing the result of the test suite.
> Update expected errors in tests, post w3c/specberus#173

- package.json
TODO: move the 3rd party checker to npm
> @dontcallmedom migrated the 3rd-party-checker to the W3C account

- .istanbul.yml
- .jshintignore
- functions.js
- lib/document-downloader.js
- lib/history.js
- lib/json-http-service.js
- lib/orchestrator.js
- lib/request-state.js
- lib/third-party-resources-checker.js
- test/test-history.js
- test/test-job.js
- test/test-json-http-service.js
- test/test-orchestrator.js
- test/test-request-state.js
64 tests before, 112 tests after (**48 new tests**). Most of them are dead simple but that will help detect issues when refactoring small or big portions.
The scary part is the code coverage: it is marked as **98%** at the moment, while it will go down to **62%** when this PR is merged. However, do not get fooled, the overall coverage *does* increases with this PR.
This comes from the fact that this PR asks [Istanbul](https://github.com/gotwarlost/istanbul) to cover all source files where it used to take into account only files that were traversed by the tests. It means that source files that were absolutely not tested... were not counted! Not very accurate.
A question for @tripu: should we add `app.js` to the files ignored by the coverage? On one hand it seems like cheating, on the other …
> Add tests to PR #84

- lib/document-downloader.js
- test/test.js
The bug fix is essentially at [line 78](https://github.com/w3c/echidna/pull/161/files#diff-bac32d994d58faa28bb71801bbf1de35R78), but I cleaned up some other things around and added a docstring (yes, just for one function of the file :p).
> Fix #160: Make sure filenames and destination files lists match after sanitizing

- CONTRIBUTING.md
- README.md
- app.js
- sendmail.sh
(I know&hellip; these are different issues, and should be different PRs. I use `tripu/miscellanea` for bunches of trivial fixes that usually can be safely processed together. It was only later that I saw that was not the case this time. If anything here is controversial, I'm happy to split into different PRs, of course :¬)
* Fix [bug](https://github.com/w3c/echidna/commit/36c3fc75f2173a8d2b7fb8052ed31bec8ef63369#diff-0364f57fbff2fabbe941ed20c328ef1aR147): missing space between command-line arguments sent to the *sendmail* script.
* Two improvements to notifications sent to the mailing list:
* Subject line more compact, easier to parse quickly when browsing mail archives, or when only the beginnings of subject lines are visible, eg on a narrow mail client:
```
[W3C Publication] Success: …
```
> Mail notifications: fix one bug, and improve subject lines and messages

- test/drafts/navigation-timing-2/meta.json
- test/test.js
Kind of related to https://github.com/w3c/echidna/pull/159#issuecomment-95673615
@plehegar, any idea on how we could avoid this situation in the future, by chance?
> Update navigation-timing-2 draft and fix test

- app.js
Because `NODE_ENV` is set in the code only [in `test/test.js`](https://github.com/w3c/echidna/blob/master/test/test.js#L4) (to `'dev'`), the expression `process.env.NODE_ENV === 'production'` was always `false`. Thus the first clause of the condition never executed¹.
Apart from that, [the default value of the app setting `view` is `process.cwd() + '/views'`](http://expressjs.com/4x/api.html#app.set), so there is no need to set it manually. Only the directory for static content `assets/` needs to be set, as described [here](http://expressjs.com/starter/static-files.html). No need to use `dist/`directories either as we're not using Grunt tasks for configuration management.
-- 
¹ `NODE_ENV` is still set to `production` manually in the command line when deploying, as described in the …
> Fix express directory for static assets

- test/views/index.html
- views/index.html
- Removed the trailing slashes
- Removed the unnecessary `type` attribute for `style`, `link` and `script` (see [this](http://stackoverflow.com/a/6239035/1935861))
- Removed unnecessary `shortcut` value for `rel` attribute of the favicon
> HTML markup cleanup

- test/drafts/navigation-timing-2/meta.json
See #185. It's happened again.
Last time I update this manually. Let's think a better way to do this.
> Update navigation-timing-2 draft to reflect latest version (again)

- package.json
- `chai-immutable` leaves `0.y.z` versions to go to `1.y.z` versions
- `chai` goes to version 3+
- `chai-as-promised` goes to version `5.1.0` to support chai 3 in its `peerDependencies`
> Update outdated devDependencies

- test/test.js
Every time there's a new version of the [navigation timing 2 spec](http://www.w3.org/TR/navigation-timing-2/) we have to [manually update the metadata for the `navigation-timing-2` test](https://github.com/w3c/echidna/commits/master/test/drafts/navigation-timing-2/meta.json) to avoid an error in the test suite (`headers.dl.latest-is-not-previous`) that [breaks the builds](https://travis-ci.org/w3c/echidna/jobs/70174278)&nbsp;&mdash;&nbsp;sometimes for days.
To avoid these false negatives, and for the time being, let's remove that particular test.
See #205.
> Comment out offending test temporarily

- .travis.yml
- package.json
Run [`nsp audit-package`](https://github.com/nodesecurity/nsp#nsp-audit-package) during the CI cycle.
(This build fails only because of the reasons explained in #206.)
> Check dependencies against nodesecurity.io DB as part of CI

- .travis.yml
It's the version we use in production, after all.
> Have Travis building using Node.js 0.12.x too

- .travis.yml
#207 reminded me of this. I recently discovered that, for Node.js, even versions were stable and odd versions were unstable. So much for semantic versioning!
Currently, Node.js ecosystem is as follows:
- `0.12`: Stable
- `0.11`: Unstable, not maintained anymore
- `0.10`: Maintenance
See https://github.com/joyent/node/blob/master/ChangeLog.
Therefore, `0.11` can safely be removed from the build matrix.
> Remove unstable node version from the Travis CI builds

- .travis.yml
@astorije [reminded us of this](https://github.com/w3c/echidna/pull/204#discussion_r34558952).
> Travis: remove explicit "npm run nsp" (ran automatically as part of "npm test")

- lib/specberus-wrapper.js
- package.json
- test/drafts/frame-timing-2/meta.json
- test/drafts/frame-timing/meta.json
- test/drafts/nav-csserror/meta.json
- test/drafts/nav-csswarning/meta.json
- test/drafts/nav-missingfiles/meta.json
- test/drafts/navigation-timing-2-generated/meta.json
- test/drafts/navigation-timing-2/meta.json
- test/drafts/navigation-timing/meta.json
- test/drafts/resource-timing/meta.json
- test/drafts/webrtc-stats/meta.json
As per [proposed process 1 September 2015](http://www.w3.org/2015/Process-20150901/).
See also [the roll-out plan](https://www.w3.org/Team/wiki/Process2015#Echidna_.26_Specberus).
This addresses #213.
This PR is intended as a place for tests and discussion for a while.
:warning: **Do not merge until 1 Sep 2015.**
:warning: **Will only work with Specberus `1.2.0` or greater**; remember to tag Specberus before merging and deploying this change in Echidna.
> Adapt code to Process 2015

- config.js.example
That slash is already added [here](https://github.com/w3c/echidna/blob/master/app.js#L109).
> Temporary http location doesn't need a trailing slash

- .travis.yml
- CONTRIBUTING.md
- README.md
- package.json
* Node.js &ge; `4.1.2`
* npm &ge; `3.3.6`
* Update also Travis environment
* Update docs accordingly
Fixes #234.
@deniak: please merge this in sync with w3c/specberus#263 and w3c/spec-generator#18, to be able to [update Node.js and npm in production](https://github.com/nodesource/distributions#manual-installation) right after.
> Migrate to Node.js 4.x

- package.json
Major `nsp` upgrade (still reports a vulnerability related to `specberus`/`socket.io` though).
```
┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ ms                                                                                            │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.6.2                                                                                         │ …
```
> upgrade nsp

- lib/document-downloader.js
If a manifest lists urls, echidna will create sub-folders:
```
index.html?specStatus=WD;shortName=foobar respec
https://www.w3.org/StyleSheets/TR/W3C-WD
https://www.w3.org/Icons/w3c_home
https://www.w3.org/StyleSheets/TR/logo-WD
```
see https://github.com/w3c/html-aria/pull/17/files
That PR forbids resources having `://` in its name.
> urls in manifest shouldn't be allowed

- app.js
- lib/document-downloader.js
- lib/orchestrator.js
- package.json
PR #241 didn't include the tar upload to echidna. This is a [problem for some WGs](https://lists.w3.org/Archives/Public/spec-prod/2015OctDec/0080.html).
That PR should fix that.
To upload the tar via `curl`:
```
curl 'http://<echidnahost>/api/request' -F "tar=@/some/path/spec.tar" -F "decision=<decision>" -F "token=<token>"
```
fix #243
> support for tar upload

- lib/orchestrator.js
- lib/publisher.js
**Do not merge** this before https://github.com/w3c/specberus/pull/331
Fix #277
> Specberus.extractMetadata now extracts all the metadata

- .travis.yml
- package.json
v4 is LTS; v5 is the one we use now in production; v6 will become LTS when 5 is not maintained any more.
> Test always with Node.js v4, v5 and v6

- lib/user-checker.js
Some users belong to ldap groups that don't match the regex. Check if there's a match before returning the group.
> check if the memberOf regex matches before returning the group

- lib/specberus-wrapper.js
- test/test.js
This will work OK **after** w3c/specberus#371 is merged.
In the meantime, to test: edit `package.json` to specify the Specberus dependency as
```json
"specberus": "https://github.com/w3c/specberus.git#tripu/fix-metadata"
```
and `npm install`.
> Adapt Specberus wrapper and tests to new metadata structure

- lib/orchestrator.js
- lib/publisher.js
- lib/specberus-wrapper.js
- test/test.js
Specberus now offers a service to extract all the metadata. The name of the parameters passed to the backend don't match what's expected. This PR fixes that.
> sync metadata extracted by specberus and parameters passed to the backend

- .nsprc
- package.json
- test/mocha.opts
- views/index.html
* Move Mocha options to its own config file.
* Sort dependencies alphabetically.
* Make sure we use latest `third-party-resources-checker`, which solves one of the npm deprecation warnings mentioned in #256.
* Have a slightly better `viewport` meta tag.
* Add temporary nsp exceptions file to mute advisories 106 &amp; 120.
> Omnibus PR

- sendmail.sh
Failure with results containing a `&` are not shown in the notification email because it's interpreted by bash. See https://lists.w3.org/Archives/Public/public-tr-notifications/2016Sep/0072.html
> escape & in the result to avoid conflict with sendmail.sh

- sendmail.sh
Building up on #352.
This should fix **the URI part** (eg, in [`https://lists.w3.org/Archives/Public/public-tr-notifications/2016Sep/0093.html`](https://lists.w3.org/Archives/Public/public-tr-notifications/2016Sep/0093.html) the URI in both the subject and the body is missing `&md-status=WD` at the end; see [the Travis file](https://github.com/w3c/permissions/blob/master/.travis.yml#L13)).
> sendmail script: escape ampersand in param $3 too

- lib/orchestrator.js
When a large tar file is submitted (10+Mb containing 300+ files), Echidna starts the next jobs before all the files get extracted. This leads to errors like 'No Overview.html found' or worse, 'Successful publication' but [incomplete](https://twitter.com/JulezRulez/status/785455267680968706).
This comes from a race condition where the tar hasn't been not completely copied and the extraction starts.
That PR aims at solving the issue.
> Race condition when submitting large tar files

- lib/publisher.js
The jobs in the orchestrator are using the *state* metadata and not the metadata from specberus directly so we need to use the property names from the extractor job, ie [*editors* instead of *editorIDs](https://github.com/w3c/echidna/blob/master/lib/orchestrator.js#L246)
> wrong metadata name passed to the job publisher

- app.js
Also, indent columns to make them more readable.
This:
```
Echidna: 1.11.6
Specberus: 3.2.0
id: 3.2.0
Decision: https://foo.bar/baz.html
```
becomes:
```
Echidna:   1.11.6
Specberus: 3.2.0
Job ID:    92898672-4f4b-8dda-b9d8-75229cfa3aa5
Decision:  https://foo.bar/baz.html
```
> Fix value of job IDs in success mail notifications

- .travis.yml
- package.json
- test/lib/testserver.js
- test/test.js
* Remove deprecated tests that were commented out and other comment.
* Travis notifications on IRC: one line; less noise.
* Update `node-uuid` ([David thinks we're using an insecure version](https://david-dm.org/w3c/echidna)) and `express`.
> Various minor changes

- .jscs.json
- app.js
Closes #420.
The API understands a new optional parameter `dry-run`, and [interprets `true` if its value equals `'true'` (case-insensitive)](https://github.com/w3c/echidna/blob/tripu/dry-run/app.js#L88). Examples:
```bash
$ curl […] -d 'dry-run=true'
$ curl […] -d 'dry-run=TRUE'
$ curl […] -d 'dry-run=yes'    # false; equivalent to not setting the param at all
```
If `dry-run` is set to true, the document is not published, and no e-mail notification is sent (the only way to check results is then via the `status` method of the API).
If/when this is merged and deployed, I'll update [the wiki](https://github.com/w3c/echidna/wiki/How-to-use-Echidna) and I'll send a notice to the [spec-prod ML](https://lists.w3.org/Archives/Public/spec-prod/).
> Implement --dry-run feature

- .jshintrc
- lib/user-checker.js
Echidna should check that the requester is participating in *at least* one WG delivering the spec.
Fix #429 
cc @dontcallmedom
> Group participation fix

- package.json
Covered by [automatic tests](https://coveralls.io/builds/11517160/source?filename=lib%2Fdocument-downloader.js#L89).
> fix(package): update tar-stream to version 1.5.4

- .travis.yml
- package-lock.json
- package.json
* v4 is superseded and too old.
* v5 deprecated.
* v8 is the new LTS version.
cf [`github.com/nodejs/LTS`](https://github.com/nodejs/LTS#lts-schedule)
**In or around 1 Apr:** restart the Travis build, test & confirm, merge.
> Adapt to Node.js release schedule

- .nsprc
- lib/document-downloader.js
- package.json
- test/drafts/nav-csserror/meta.json
- test/drafts/nav-csswarning/meta.json
For Express, I rejected greenkeeper's automatic upgrade to [that pre-release](https://github.com/expressjs/express/releases/tag/5.0.0-alpha.6) earlier today, as I usually do, without realising it's the best way to prevent one of the vulnerabilities. Using that now.
The rest of vulns originate in Specberus. This PR depends on Specberus `3.4.1`, which does not exist yet.
Please merge w3c/specberus#684 and tag and publish that new version of Specberus first&nbsp;&mdash;&nbsp;then come here and restart the Travis build, and check that this PR passes.
**Update:** depends on w3c/specberus#690 and future Specberus `3.4.2`
> Fix nsp errors

- .nsprc
- test/drafts/nav-csserror/index.html
- test/drafts/nav-csswarning/index.html
* Fix two test drafts for Specberus + CSS testing ([this transition](https://github.com/w3c/specberus/pull/697/commits/beebb00274756bcc7d9e1dc1c531ab9fcd2b2a96) expired on 1 Dec)
* Stop ignoring [nsp advisory no. 479](https://nodesecurity.io/advisories/479)
> Fix the build with a couple of updates

- test/drafts/nav-csserror/meta.json
- test/drafts/nav-csswarning/meta.json
Two tests are failing because we no longer accept documents on process 2017. That PR switches these test documents to process 2018.
> Fix tests after switch to process 2018

- app.js
- package.json
This was causing a warning from npm.
The build is still failing due to [a new security advisory](https://www.npmjs.com/advisories/736) &mdash; but that one's coming from Specberus, so let's fix it there.
**Update:** Specberus is already cured, it's just a matter of us tagging a new release and publishing it on npm.
> Package node-uuid is deprecated; use uuid instead

- .travis.yml
&hellip;whenever Echidna gets the next release of Specberus
cf w3c/specberus#786
> Use new "W3C_API_KEY" for Specberus in Travis builds

- app.js
Annotate a request can be helpful to identify a specification if echidna hasn't been able to extract the metadata.
Fix #831
> add optional parameter to annotate a request

- lib/json-http-service.js
- lib/mailer.js
Recently, Echidna started to report an error after a request in the 'publish' job fail, e.g. https://labs.w3.org/echidna/api/status?id=54938aec-857a-424f-8427-40592dee5155
The bug is due to a recent code style refactoring: https://github.com/w3c/echidna/commit/106ce6d97b38828e99c7a4076cc7bd3b95c7e256#diff-68e1d1c7217131e9452081b60e63a80f81a96d44d2d1ded424ffd72a08b58df4R53
The publisher tries to deconstruct the result (https://github.com/w3c/echidna/blob/main/lib/publisher.js#L67) but since the name of the variable changed, it fails.
The PR fixes that issue and a small lint error.
> Fix decontruct

- package.json
Reverts w3c/echidna#951
This contains a breaking change with passport-http.
> Revert "Bump passport from 0.4.1 to 0.5.0"

- .gitignore
- .istanbul.yml
- .nycrc
- package.json
- test/mocha.opts
nyc replaced the regular istanbul CLI, so this switches over to that. moved the Mocha config to the package.json since the `mocha.opts` has also been deprecated
> chore: migrate istanbul to nyc

- lib/ip-checker.js
- package.json
It seems some GH actions are now running from servers that aren't listed in the 'actions' range.
That PR includes other ranges when checking the IP
Fix #1049
> GH actions IPs can be in a different range from what /meta returns

- .github/workflows/node.js.yml
Should be less noisy with Dependabot, and matches the other built-in actions
> ci: unpine setup-node to v3

- .cspell.json
- app.js
resolves https://github.com/w3c/echidna/issues/1039, also update https://github.com/w3c/echidna/wiki/How-to-use-Echidna#tar-file
After this change, when using `curl --anyauth ...`, the server receives request twice. It gives a 401 with header `WWW-Authenticate: Basic realm="W3CACL"` when no user-password is sent, and '202 Accepted' when having the right credentials.
> Add server header when no auth

- lib/json-http-service.js
- lib/orchestrator.js
- lib/token-checker.js
- test/test-json-http-service.js
W3C will soon change its authentication method. This PR adds a special header to bypass SSO so we can still rely on basic auth to access the endpoints we need.
> use special header to bypass W3C SSO

- README.md
minor heading clarification: Echidna is not an editor, Echidna is for spec editors
> editorial: clarify as a spec editor
