test/lib/testserver.js
Fixing https://github.com/w3c/echidna/issues/34
=> Iterate through ports to run the test server

app.js, package.json
This commit also applies the version strategy suggestion **(1b)** explained in #50.
=> Apply fixed major/flexible minor+patch for dependencies and devDependencies + dependency cleanup

README.md
=> fix documentation using npm start

app.js
See [@astorije's comment](https://github.com/w3c/echidna/pull/39#issuecomment-71855010).
=> W3C prefix: replace flexible regex with a more strict string

sendmail.sh
=> Only send mails when in production

README.md, app.js, assets/scripts/behaviour.js, config.js.example, package.json, views/index.html
=> Generate unique id to identify the job

app.js, lib/document-downloader.js, test/test.js
Instead of a parameter, let's do:
if (content.trim().charAt(0) !== '<') {
// it's a manifest
}
=> Added automatic detection of manifest and removed isManifest parameter

Gruntfile.js, app.js, config.js.example, functions.js, lib/document-downloader.js, lib/history.js, test/lib/cssvalidator.js, test/lib/htmltemplate.js, test/lib/htmlvalidator.js, test/lib/testserver.js, test/lib/tokenchecker.js, test/lib/utils.js
As discussed in #81, this reformats files to comply with the [style guide](https://github.com/w3c/echidna/wiki/Coding-style-guide).
Note that any other modification on the project before this is merged will result in a world of pain due to difficult rebases... :-)
Any chance we can merge this before fully agreeing on the style? Then I suggest we use #81 to agree on the style, and then I'll make the changes to the guide followed by changes in the code itself.
=> Reformat code according to the coding style

README.md
For reference, see https://lists.w3.org/Archives/Public/spec-prod/2015JanMar/0011.html
=> Note in README local setup of the full system is not possible

package.json
Super simple PR to review :-)
Of course, this should not be merged before https://github.com/w3c/specberus/pull/158 is merged and Specberus makes it `1.0.0` on the npm repository...
=> Use npm's Specberus rather than GitHub's

functions.js
Wait for w3c/specberus#153 to be merged before merging this.
=> Use the Echidna-specific profile of Specberus

package.json, test/test.js
This uses a plugin I made on my free time (https://github.com/astorije/chai-immutable). ~~It is not on the npm repository yet but will be soon.~~ [It is now](https://www.npmjs.com/package/chai-immutable) \o/
=> Simplify tests

views/index.html
=> Restyle front page to look good on small screens too

lib/document-downloader.js, package.json
=> fix downloader sub-directories missing

README.md
Extending #131 hoping to be clearer and more explicit.
=> Make the README clearer regarding what should editors and developers read to use the tool

README.md
=> Get rid of the code-surrounded links and fix a typo

config.js.example, views/index.html
At least for now. See PR #144.
=> Restrict CORS to w3c.github.io

lib/orchestrator.js, test/test-orchestrator.js
Echidna is actually broken without this fix, no publications can be made! Sorry I missed that...
Again, the enumeration thingy is not pretty and was argued over before, but this should look nicer when a state machine jumps in.
=> Fix wrong orchestration ending detection, preventing Echidna to run at all

test/drafts/navigation-timing-2/meta.json
Like we did in a79f46e10495a3f9ff6f66cd3bafb8620f9ce2ba.
=> Update navigation-timing-2 draft to reflect latest version

app.js, lib/orchestrator.js
=> Fix wrong URL in e-mail notifications after successful publication

doc/presentation.md
* Add a few more useful links, eg to examples of e-mail notifications
* Better wording about ReSpec on labs
* Other fixes
=> Presentation: tweaks and corrections

app.js
=> in case of failure, send the whole request data instead of the RequestState only

app.js
=> json result: dump requests[id] to include id, version, uri, etc

package.json, test/test-history.js, test/test-job.js, test/test-json-http-service.js, test/test-request-state.js
This feature was added by [Chai 3.1.0](https://github.com/chaijs/chai/releases/tag/3.1.0) a few days ago but it was buggy until [Chai 3.2.0](https://github.com/chaijs/chai/releases/tag/3.2.0) released a few minutes ago.
=> Simplify tests against frozen objects

.travis.yml
&hellip;[as @astorije suggested](https://github.com/w3c/echidna/pull/210#discussion_r35340426).
=> Travis: move “nsp” to “script” section

views/index.html
=> Adapt code style to new version of jscs

lib/orchestrator.js, lib/publisher.js, lib/specberus-wrapper.js, package.json, test/drafts/charmod-norm/index.html, test/drafts/charmod-norm/meta.json, test/drafts/frame-timing-2/meta.json, test/drafts/frame-timing/meta.json, test/drafts/nav-csserror/meta.json, test/drafts/nav-csswarning/meta.json, test/drafts/nav-missingfiles/meta.json, test/drafts/navigation-timing-2-generated/meta.json, test/drafts/navigation-timing-2/meta.json, test/drafts/navigation-timing/meta.json, test/drafts/resource-timing/meta.json, test/drafts/webrtc-stats/meta.json, test/test.js
Start implementing non-rec track documents in echidna
=> Process both REC track and non-REC track documents

app.js
=> escape single quote in the result before passing it to the sendmail command

lib/document-downloader.js
=> fix escaping issue if the tar doesn't have an Overview.html

lib/orchestrator.js
=> child_process.exec reject with stderr to improve feedback to the user

lib/orchestrator.js
=> apostrophe breaks the command that sends email

sendmail.sh
=> send UTF-8 emails

lib/specberus-wrapper.js
I think you meant to halt execution here, no?
=> fix(specberus-wrapper): return on rejection

.nsprc
This reverts commit 8f388330563511221c589dc570db56f89c9ac071.
cf #358.
Weird.
=> Revert "Remove nsp exceptions; there are no errors now"

.nsprc, package.json
=> Use current Specberus and ditch nsp exceptions file

app.js, sendmail.sh
Fix https://github.com/w3c/specberus/issues/529
=> include decision and request id in the notification email

package.json
=> fix(package): update file-type to version 5.1.0

package.json
=> fix(package): update file-type to version 5.1.1

package.json
=> fix(package): update file-type to version 5.2.0

package.json
=> fix(package): update promise to version 7.3.1

package.json
=> chore(package): update jsdoc to version 3.5.1

package.json
=> fix(package): update file-type to version 6.1.0

package.json
=> fix(package): update file-type to version 6.2.0

package.json
=> fix(package): update file-type to version 7.0.1

package.json
=> fix(package): update file-type to version 7.1.0

package.json
=> fix(package): update file-type to version 7.2.0

package.json
=> fix(package): update file-type to version 7.3.0

package.json
=> fix(package): update file-type to version 7.4.0

package.json
=> fix(package): update file-type to version 7.6.0

package.json
=> fix(package): update file-type to version 7.7.1

package.json
=> fix(package): update tar-stream to version 1.6.0

package.json
=> fix(package): update tar-stream to version 1.6.1

package.json
=> fix(package): update file-type to version 8.0.0

package.json
Thanks for letting your CI be my guinea pig while I test the v2 :D
(I suggest you do not merge until v2, but I want to see a green check on your end before being confident to release v2)
=> Update chai-immutable to v2

lib/transition-checker.js
Echidna fails on the transition checker if the first issue found doesn't match on the title
=> fix logic error in issue lookup

assets/mail-templates/failure.txt, assets/mail-templates/success.txt, lib/mailer.js
I think this should fix all issues listed on #605, except item no. 3 (*&ldquo;Improve template to report issues?&rdquo;*)
=> Fix certain fields in new mail messages

package.json
=> fix(package): update multer to version 1.4.1

package.json
=> fix(package): update file-type to version 10.4.0

lib/mailer.js
=> check that the 'This Version' url does match the regex before extracting the shortname

package.json
=> fix(package): update file-type to version 10.6.0

package.json
=> fix(package): update nodemailer to version 5.1.1

package.json, test/drafts/nav-csserror/index.html, test/drafts/nav-csswarning/index.html
=> Specberus 4.1.1 + test fix

package.json, test/test.js
Closes #688 #687 #679 #677 #674 #668 #666 #665
=> update deps + fix tests + remove audit from build script

.gitignore, DEVELOPMENT.md, app.js, config-dev.js, lib/history.js, lib/orchestrator.js, lib/specberus-wrapper.js, package.json, test/lib/testserver.js, test/lib/tokenchecker.js, test/test.js
update testserver so it can start all the dependencies needed by echidna. This should help getting started with Echidna
=> update local test server to start all the dependencies needed to test the whole workflow of echidna

.github/workflows/node.js.yml, package.json
=> Update to add Node16

lib/transition-checker.js
find in the whole comment rather than the very beginning. resolves #910
=> Loose the check for director & comm approval

lib/orchestrator.js, lib/publisher.js, lib/specberus-wrapper.js, lib/transition-checker.js, package.json, test/test.js
=> Support for REC with candidate amendments

lib/transition-checker.js
Fix reported issue https://github.com/w3c/echidna/pull/1073#pullrequestreview-1117879416
=> remove duplicated status

.github/workflows/node.js.yml
=> Remove irc notification

app.js, assets/mail-templates/failure.txt, assets/mail-templates/success.txt, lib/mailer.js
=> Add decision link in email template

.github/workflows/node.js.yml, lib/mailer.js, lib/specberus-wrapper.js, test/test.js
Fix specberus version mentioned in email, resolves #1098
=> Fix specberus version mentioned in email

app.js, lib/orchestrator.js, lib/transition-checker.js
- Don't close transition issue when dry-run, closes #680 
- Change output msg when dry-run, closes #582
=> Address dry-run issues

lib/mailer.js
Fix issue with emails with parameters coming from a promise
=> Mailer body patch

.github/workflows/node.js.yml, package.json
Node 20 is out. That PR includes support for the new version
=> support node 20

lib/specberus-wrapper.js, lib/transition-checker.js, package.json
=> handle Draft Registies

package.json, test/drafts/nav-csserror/index.html, test/drafts/nav-csserror/meta.json, test/drafts/nav-csswarning/index.html, test/drafts/nav-csswarning/meta.json
Accept 20231103 process document
=> Specberus 10.0.0

package.json
=> octokit/core 6.0.1
